@Library('k8s-jenkins-sharedLibraries') _
pipeline{
    agent {
        kubernetes{
            cloud 'kubernetes'
            namespace 'pe-devops'
            defaultContainer 'jnlp'
            yaml getPodTemplatePR()
        }
    }
    stages {
        stage('Get-Data') {
            steps {
                script {
                    container('jnlp') {
                        sh "ls -lha"
                        projectInfo = utils.getProjectInfo(URL_PROJECTS_YAML_RAW)
                        println projectInfo
                    }
                }
            }
        }
    }
}