backend:
  java:
    java-demo:
      ssh_clone_url: 'git@github.com:niels-baltodano/java-demo.git'
      cmd_build: 'mvn clean package'
frontend:
  node:
    node-demo:
      ssh_clone_url: 'git@github.com:niels-baltodano/node-demo.git'